nav:

    - Accueil: index.md

    - Le projet : 
        - Présentation générale : pages/presentation_generale_outil.md
        - Méthodologie : pages/methodologie.md
        - Collectif & Partenaires : pages/equipe_projet.md

    - Les besoins : 
        - Les besoins vitaux : 
            - pages/besoins/bv1.md
            - pages/besoins/bv2.md
            - pages/besoins/bv3.md
            - pages/besoins/bv4.md
            - pages/besoins/bv5.md
        - Les besoins essentiels : 
            - pages/besoins/be1.md
            - pages/besoins/be2.md
            - pages/besoins/be3.md
        - Les besoins induits : 
            - pages/besoins/bi1.md
            - pages/besoins/bi2.md
            - pages/besoins/bi3.md
        
    - L'outil: pages/demande_telechargement.md

site_name: Diag360 - Résilience territoriale
site_author: Nicolas Brémond et le collectif Diag360
site_description: Outil utile au diagnostic et à l’appropriation des enjeux territoriaux sur objectifs de subsistance, gestion de crise et soutenabilité.
site_url: https://konsilion.github.io/diag360
repo_url: https://github.com/Konsilion/diag360
repo_name: konsilion/diag360
edit_uri: edit/master/mkdocs/docs/


extra:
  generator: false

theme:
    name: material
    features:
      - content.action.edit
      - navigation.indexes
      - navigation.tracking
      - navigation.top
      - navigation.tabs
      - navigation.tabs.sticky
    language: fr
    palette:
        primary: blue grey
        accent: green

plugins:
  - macros
  - search

markdown_extensions:
  - tables
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.blocks.caption
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.arithmatex:
      inline_wrap: '$'
      generic: true

extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra_css:
  - https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.1/css/all.min.css
  - personnal.css
  
copyright: Une méthode développée avec ❤ par le Collectif Diagnostic 360° & codée par Nicolas Brémond - © 2024 by Frédéric Haas is licensed under CC BY-NC-ND 4.0 - Made with <a href="https://squidfunk.github.io/mkdocs-material/" target="_blank">Material for MkDocs Insiders</a>
